---

- hosts: all
  become: yes
  pre_tasks:

  - name: update repo cache (CentOS)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

- hosts: all
  become: yes
  roles:
  - base

- hosts: workstations
  become: yes
  roles:
  - workstations

- hosts: web_servers
  become: yes
  roles:
  - web_servers

- hosts: db_servers
  become: yes
  roles:
  - db_servers

- hosts: file_servers
  become: yes
  roles:
  - file_servers
