---

- hosts: all
  become: yes
  pre_tasks:

  - name: update repo cache (CentOS)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

- hosts: all
  become: yes
  tasks:
  - name: add ssh key for simone
    tags: always
    authorized_key: 
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBHS8bqvh0x5LgJZFCRDYo5x5vMdb/iVBy9GzE+Ypx26 ansible"
  
- hosts: workstations
  become: yes
  tasks:
  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: yes
  tasks:

  - name: install apache server and php
    tags: apache,centos,httpd
    yum:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
    # when: ansible_distribution in ["Debian", "Ubuntu"]
    # when: ansible_distribution == "CentOS" and ansible_distribution_version == "8.2"
  - name: start httpd server
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: change email address for admin
    tags: apache, centos, httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.com
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: restart httpd
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: apache,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: yes
  tasks:

  - name: install mariadb package
    tags: centos,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: yes
  tasks:
  
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
